name: Tests
on: [push]
jobs:
#  clippy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: clippy
#        run: make clippy
  go-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: is this necessary?
      - name: Setup Go 1.17.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.17.x'
      - name: build
        run: make build
      - name: go-tests
        run: make test

#  rust-unit-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      # TODO: does this need cargo and rust installed?
#      - name: rust-tests
#        run: |
#          cd libtfhe-wrapper && cargo test
