name: Tests
on: [push]
env:
  GOPRIVATE: "github.com/fhenixprotocol/decryption-oracle"
jobs:
  go-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git for HTTPS
        run: |
          git config --global url."https://cashmaney:${{ secrets.CI_TOKEN }}@github.com".insteadOf https://github.com

      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: restore cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: build
        run: make build
      - name: go-tests
        run: make test

  rust-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git for HTTPS
        run: |
          git config --global credential.helper store
          cat > ~/.git-credentials <<- EOM
          https://${{ secrets.CI_TOKEN }}@github.com
          EOM
          git config --global url."https://${{ secrets.CI_TOKEN }}@github.com".insteadOf ssh://git@github.com
      - uses: actions/checkout@v4
      - name: restore cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: rust-tests
        run: |
          cd libtfhe-wrapper && cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git for HTTPS
        run: |
          git config --global credential.helper store
          cat > ~/.git-credentials <<- EOM
          https://${{ secrets.CI_TOKEN }}@github.com
          EOM
          git config --global url."https://${{ secrets.CI_TOKEN }}@github.com".insteadOf ssh://git@github.com

      - uses: actions/checkout@v4
      - name: restore cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: clippy
        run: make clippy

