name: Tests
on: [push]
jobs:
#  clippy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: clippy
#        run: make clippy
  go-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: does this need go installed?
      - name: go-tests
        run: make test

#  rust-unit-tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      # TODO: does this need cargo and rust installed?
#      - name: rust-tests
#        run: |
#          cd libtfhe-wrapper && cargo test
